### ISSUE TITLE
Short ToDo List for Tetris 

### ISSUE THREAD

**Issue by Maze7** [Maze7/Tetris#21]
A short ToDo list for the tetris module.

1. [x] GameOver Screen
2. [x] Score Screen (show scores) and safe scores on closing
3. [x] Encrypt score file
4. [x] Sound during game
5. [x] Sound effect if block hits another
6. [x] Difficulty

**Comment by Maze7** [comment]
Encryption impleneted in #28

**Comment by Maze7** [comment]
Finished ScoreScreen in 6e9c6c9b26dd85074572976106e46f2979990f05

**Comment by LukasK-roboyor** [comment]
Difficulty in 9fa28afd7be3eecb47d1724543e107675750624e

**Comment by Maze7** [comment]
The small sound effeckts wasn implement in tetris but in Snake and FlappyBird
